#!/usr/bin/env python3
"""Generate the three eval variant overlays.

Each overlay is copied on top of app-repo/ to produce a run directory.

  a  new flow, empty memory, no identifiers in app code   -> steps 0-5
  b  post-build resume: identifiers in code, memory + working files seeded -> steps 6-9
  c  green loop: existing test, failure artifacts on disk, backend 404     -> diagnosis
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
VAR = ROOT / "variants"

SCAFFOLD_INDEX = """\
# Memory index (compact — detail files loaded on demand)

_(empty — generated by the agentqa-write-test skill's scripts/memory-index.py as notes are added)_
"""

# ---------------------------------------------------------------------------
# identifiers, as they look once step 4 has been done and the human has built
# ---------------------------------------------------------------------------

IDS_INTRO = """\
        btnLogin.accessibilityIdentifier = "login_intro_login_button"
        btnFree.accessibilityIdentifier = "login_intro_free_button"
"""

IDS_LOGINVIEW = """\
        usernameTextField.accessibilityIdentifier = "login_username_field"
        passwordTextField.accessibilityIdentifier = "login_password_field"
        checkBoxTermImgView.accessibilityIdentifier = "login_terms_checkbox"
        termsLink.accessibilityIdentifier = "login_terms_link"
        btnLogin.accessibilityIdentifier = "login_submit_button"
        errorLabel.accessibilityIdentifier = "login_error_label"
"""

IDS_TABBAR = """\
        homeTab.accessibilityIdentifier = "home_home_tab"
        liveTab.accessibilityIdentifier = "home_live_tab"
        profileTab.accessibilityIdentifier = "home_profile_tab"
"""


def with_identifiers():
    """Return {relpath: content} for the Swift files, identifiers added."""
    base = ROOT / "app-repo" / "mytvb2c" / "Sources"
    out = {}

    p = "mytvb2c/Sources/Login/IntroductionContentViewController.swift"
    t = (base / "Login" / "IntroductionContentViewController.swift").read_text(encoding="utf-8")
    t = t.replace('        NotificationPermission.requestIfNeeded()\n',
                  IDS_INTRO + '        NotificationPermission.requestIfNeeded()\n')
    out[p] = t

    p = "mytvb2c/Sources/Login/LoginView.swift"
    t = (base / "Login" / "LoginView.swift").read_text(encoding="utf-8")
    t = t.replace('        errorLabel.isHidden = true\n',
                  '        errorLabel.isHidden = true\n\n' + IDS_LOGINVIEW)
    out[p] = t

    p = "mytvb2c/Sources/Home/MainTabBarController.swift"
    t = (base / "Home" / "MainTabBarController.swift").read_text(encoding="utf-8")
    t = t.replace('        let home = HomeViewController()',
                  IDS_TABBAR + '\n        let home = HomeViewController()')
    out[p] = t
    return out


# ---------------------------------------------------------------------------
# memory notes shared by variants b and c
# ---------------------------------------------------------------------------

FLOW_LOGIN = """\
---
title: login
type: flow
tags: [login, authentication]
summary: Intro → login form → home tab bar, gated on a terms checkbox
last_verified: 2026-07-23
---

# login

## Observations
- [flow-step] launch → notifications permission alert (SpringBoard) → dismissed with "Don't Allow" per reviewer #login
- [flow-step] IntroductionContentViewController → press "Đăng nhập ngay" → LoginViewController #login
- [flow-step] fill username + password, tick "Tôi đồng ý với điều khoản sử dụng", press "Đăng nhập" #login
- [flow-step] success → MainTabBarController with tab bar Trang chủ / Truyền hình / Cá nhân #login
- [assertion] valid credentials + terms ticked lands on the home tab bar #login
- [edge-case] wrong credentials → inline "Sai tên đăng nhập hoặc mật khẩu" under the password field, stays on login #login
- [edge-case] terms unticked → "Vui lòng đồng ý với điều khoản sử dụng", submit is disabled #login
- [native] intro, login and home are native UIKit #login
- [web] the terms sheet is a WKWebView with no native nodes — screenshot only #login
- [quirk] the permission alert is owned by SpringBoard and appears on every wiped launch #login

## Relations
- covers [[intro]]
- covers [[login_form]]
- covers [[home]]
"""

SCREEN_INTRO = """\
---
title: intro
type: screen
tags: [login]
summary: IntroductionContentViewController — login / guest entry point
last_verified: 2026-07-23
---

# intro

## Observations
- [native] IntroductionContentViewController, UIKit xib #login
- [identifier] login_intro_login_button → IntroductionContentViewController.btnLogin; added-unverified 2026-07-23 #login
- [identifier] login_intro_free_button → IntroductionContentViewController.btnFree; added-unverified 2026-07-23 #login
- [quirk] requests notification permission in viewDidLoad, so the alert covers this screen on a wiped launch #login

## Relations
- used-by [[login]]
"""

SCREEN_LOGIN = """\
---
title: login_form
type: screen
tags: [login]
summary: LoginView — username, password, terms checkbox, submit
last_verified: 2026-07-23
---

# login_form

## Observations
- [native] LoginView loaded from a nib by LoginViewController #login
- [identifier] login_username_field → LoginView.usernameTextField; added-unverified 2026-07-23 #login
- [identifier] login_password_field → LoginView.passwordTextField; added-unverified 2026-07-23 #login
- [identifier] login_terms_checkbox → LoginView.checkBoxTermImgView; added-unverified 2026-07-23 #login
- [identifier] login_terms_link → LoginView.termsLink; added-unverified 2026-07-23 #login
- [identifier] login_submit_button → LoginView.btnLogin; added-unverified 2026-07-23 #login
- [identifier] login_error_label → LoginView.errorLabel; added-unverified 2026-07-23 #login
- [quirk] btnLogin.isEnabled is driven by termsAccepted — the checkbox must be tapped before submit #login
- [quirk] errorLabel is hidden until showError(_:) runs #login

## Relations
- used-by [[login]]
"""

SCREEN_HOME = """\
---
title: home
type: screen
tags: [home]
summary: MainTabBarController — the post-login landing surface
last_verified: 2026-07-23
---

# home

## Observations
- [native] MainTabBarController with three tabs #login
- [identifier] home_home_tab → MainTabBarController.homeTab; added-unverified 2026-07-23 #login
- [identifier] home_live_tab → MainTabBarController.liveTab; added-unverified 2026-07-23 #login
- [identifier] home_profile_tab → MainTabBarController.profileTab; added-unverified 2026-07-23 #login

## Relations
- used-by [[login]]
"""

FAILURE_WDA = """\
---
title: wda-timeout-under-load
type: failure
tags: [phantom, infra]
summary: WebDriverAgent session timeout when the host is CPU-saturated
last_verified: 2026-07-20
---

# wda-timeout-under-load

## Observations
- [symptom] `WebDriverAgent process failed to start` or a session that hangs for 60s then dies, with no app-side error #infra
- [cause] a CPU-heavy job (usually `codegraph init`) running while the simulator drives the suite #infra
- [remedy] stop the indexing job, wait for load to drop, re-run the suite once #infra
"""

INDEX_SEEDED = """\
# Memory index (compact — detail files loaded on demand)

## Flows
- **login** — Intro → login form → home tab bar, gated on a terms checkbox
  - covers: intro, login_form, home

## Screens
- **intro** — IntroductionContentViewController — login / guest entry point
- **login_form** — LoginView — username, password, terms checkbox, submit
- **home** — MainTabBarController — the post-login landing surface

## Failures
- **wda-timeout-under-load** — WebDriverAgent session timeout when the host is CPU-saturated

## Env
- env.md — build policy, credential env-var names, simulator gotchas
"""

SESSION_REQUIREMENT = """\
---
title: Session requirement — login
type: session-requirement
updated: 2026-07-23
---
## Request
Write a UI test for the login flow — the user logs in and reaches the home screen.

## Success
The user enters a valid username and password, ticks the terms checkbox, taps
Đăng nhập, and lands on the home screen with the bottom tab bar visible.

## Failure
The app stays on the login screen and shows the inline red text "Sai tên đăng
nhập hoặc mật khẩu" under the password field. It must not bounce back to intro
and must not show a modal.

## Blockers
- Notifications permission alert on first launch after a wipe → reviewer said tap "Don't Allow"
- Đăng nhập stays disabled until the terms checkbox is ticked → tick it before submitting
- No OTP/2FA on the QA account

## Environment / preconditions
staging backend; start logged out; credentials from APP_TEST_USERNAME / APP_TEST_PASSWORD.
"""

RUN_CHECKPOINT = """\
---
run_id: login-2026-07-23-01
current_step: 5
feature: login
updated: 2026-07-23
---

## Added identifiers (awaiting build+verify)
- login_intro_login_button → IntroductionContentViewController.btnLogin
- login_intro_free_button → IntroductionContentViewController.btnFree
- login_username_field → LoginView.usernameTextField
- login_password_field → LoginView.passwordTextField
- login_terms_checkbox → LoginView.checkBoxTermImgView
- login_terms_link → LoginView.termsLink
- login_submit_button → LoginView.btnLogin
- login_error_label → LoginView.errorLabel
- home_home_tab → MainTabBarController.homeTab
- home_live_tab → MainTabBarController.liveTab
- home_profile_tab → MainTabBarController.profileTab

## Hypothesis under test
Valid credentials + ticked terms checkbox lands the user on the home tab bar.

## Blocker
WAITING_FOR_HUMAN_BUILD
"""

# ---------------------------------------------------------------------------
# variant c: an existing test and its failure artifacts
# ---------------------------------------------------------------------------

PAGE_OBJECT = '''\
"""Page objects for the login flow."""
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


class IntroPage:
    LOGIN_BUTTON = (AppiumBy.ACCESSIBILITY_ID, "login_intro_login_button")
    # SpringBoard's, not the app's: it sits outside the app element tree and no
    # accessibilityIdentifier can reach it, so match the visible label.
    PERMISSION_DENY = (AppiumBy.IOS_PREDICATE, 'label == "Don\'t Allow"')

    def __init__(self, driver):
        self.driver = driver

    def dismiss_permission_alert(self):
        """reset_app_data: always restores the permission state, so this prompt
        fires on every launch. Harmless when it is not there."""
        try:
            self.driver.find_element(*self.PERMISSION_DENY).click()
        except NoSuchElementException:
            pass

    def tap_login(self):
        self.driver.find_element(*self.LOGIN_BUTTON).click()


class LoginPage:
    USERNAME = (AppiumBy.ACCESSIBILITY_ID, "login_username_field")
    PASSWORD = (AppiumBy.ACCESSIBILITY_ID, "login_password_field")
    TERMS = (AppiumBy.ACCESSIBILITY_ID, "login_terms_checkbox")
    SUBMIT = (AppiumBy.ACCESSIBILITY_ID, "login_submit_button")
    ERROR = (AppiumBy.ACCESSIBILITY_ID, "login_error_label")

    def __init__(self, driver):
        self.driver = driver

    def login(self, username, password):
        self.driver.find_element(*self.USERNAME).send_keys(username)
        self.driver.find_element(*self.PASSWORD).send_keys(password)
        self.driver.find_element(*self.TERMS).click()
        self.driver.find_element(*self.SUBMIT).click()

    def error_text(self):
        return self.driver.find_element(*self.ERROR).text


class HomePage:
    HOME_TAB = (AppiumBy.ACCESSIBILITY_ID, "home_home_tab")

    def __init__(self, driver):
        self.driver = driver

    def is_loaded(self):
        return self.driver.find_element(*self.HOME_TAB).is_displayed()
'''

TEST_FILE = '''\
"""Login flow UI tests."""
import os

import pytest

from pages.login_page import HomePage, IntroPage, LoginPage


@pytest.fixture
def credentials():
    user = os.environ.get("APP_TEST_USERNAME")
    pwd = os.environ.get("APP_TEST_PASSWORD")
    if not user or not pwd:
        pytest.skip("APP_TEST_USERNAME / APP_TEST_PASSWORD not set")
    return user, pwd


def test_login_happy_path(driver, credentials):
    """Valid credentials + accepted terms land the user on the home tab bar."""
    username, password = credentials
    intro = IntroPage(driver)
    intro.dismiss_permission_alert()
    intro.tap_login()
    LoginPage(driver).login(username, password)
    assert HomePage(driver).is_loaded(), "expected the home tab bar after login"


def test_login_rejects_wrong_password(driver, credentials):
    """A wrong password keeps the user on the login screen with an inline error."""
    username, _ = credentials
    intro = IntroPage(driver)
    intro.dismiss_permission_alert()
    intro.tap_login()
    page = LoginPage(driver)
    page.login(username, "definitely-not-the-password")
    assert page.error_text() == "Sai tên đăng nhập hoặc mật khẩu"
'''

FAILED_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
  <XCUIElementTypeApplication type="XCUIElementTypeApplication" name="MyTV" label="MyTV" enabled="true" x="0" y="0" width="393" height="852">
    <XCUIElementTypeAlert type="XCUIElementTypeAlert" name="THÔNG BÁO" label="THÔNG BÁO" enabled="true" visible="true" x="43" y="330" width="307" height="192">
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" name="THÔNG BÁO" label="THÔNG BÁO" value="" enabled="true" visible="true"/>
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" name="Đã có lỗi xảy ra, Quý khách vui lòng thử lại sau! (58)" label="Đã có lỗi xảy ra, Quý khách vui lòng thử lại sau! (58)" value="" enabled="true" visible="true"/>
      <XCUIElementTypeButton type="XCUIElementTypeButton" name="Đóng" label="Đóng" enabled="true" visible="true"/>
    </XCUIElementTypeAlert>
    <XCUIElementTypeButton type="XCUIElementTypeButton" name="login_intro_login_button" label="Đăng nhập ngay" enabled="true" visible="false" x="24" y="640" width="345" height="48"/>
    <XCUIElementTypeButton type="XCUIElementTypeButton" name="login_intro_free_button" label="Xem miễn phí" enabled="true" visible="false" x="24" y="700" width="345" height="48"/>
  </XCUIElementTypeApplication>
</AppiumAUT>
"""

VARIANTS = {}

VARIANTS["a"] = {
    ".agentqa/memory/index.md": SCAFFOLD_INDEX,
}

VARIANTS["b"] = {
    **with_identifiers(),
    ".agentqa/memory/index.md": INDEX_SEEDED,
    ".agentqa/memory/flows/login.md": FLOW_LOGIN,
    ".agentqa/memory/screens/intro.md": SCREEN_INTRO,
    ".agentqa/memory/screens/login_form.md": SCREEN_LOGIN,
    ".agentqa/memory/screens/home.md": SCREEN_HOME,
    ".agentqa/memory/failures/wda-timeout-under-load.md": FAILURE_WDA,
    ".agentqa/memory/.session-requirement.md": SESSION_REQUIREMENT,
    ".agentqa/memory/.run-checkpoint.md": RUN_CHECKPOINT,
}


def _verified(text):
    return text.replace("added-unverified 2026-07-23", "verified-in-hierarchy 2026-07-23")


VARIANTS["c"] = {
    **with_identifiers(),
    ".agentqa/memory/index.md": INDEX_SEEDED,
    ".agentqa/memory/flows/login.md": FLOW_LOGIN,
    ".agentqa/memory/screens/intro.md": _verified(SCREEN_INTRO),
    ".agentqa/memory/screens/login_form.md": _verified(SCREEN_LOGIN),
    ".agentqa/memory/screens/home.md": _verified(SCREEN_HOME),
    ".agentqa/memory/failures/wda-timeout-under-load.md": FAILURE_WDA,
    "AutomationTests/pages/login_page.py": PAGE_OBJECT,
    "AutomationTests/tests/test_login.py": TEST_FILE,
    "AutomationTests/artifacts/failed_test_login_happy_path.xml": FAILED_XML,
    ".agentqa/.eval-backend": "error_404\n",
}


def main():
    for name, files in VARIANTS.items():
        for rel, content in files.items():
            p = VAR / name / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
        # binary artifact
        if name == "c":
            png = VAR / name / "AutomationTests/artifacts/failed_test_login_happy_path.png"
            png.write_bytes(b"\x89PNG\r\n\x1a\n<mock failure screenshot: THONG BAO alert>")
        print(f"variant {name}: {len(files)} files")


if __name__ == "__main__":
    sys.exit(main())
