#!/usr/bin/env python3
"""Generate the eval variant overlays.

Each overlay is copied on top of app-repo/ to produce a run directory.

  a                new flow, empty memory, no identifiers in app code   -> steps 0-5
  b                post-build resume: identifiers in code, memory + working files seeded -> steps 6-9
  c                green loop: existing test, failure artifacts on disk, backend 404 -> diagnosis

  a-docs           = a + a `docs:` block and an SRD that MATCHES the build
                     -> the intent layer should pre-fill clarify
  a-docs-conflict  = a + a `docs:` block and an SRD that has DRIFTED from the build
                     -> live hierarchy must win, divergences must be surfaced,
                        and unverified doc claims must stay out of flows//screens/
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
VAR = ROOT / "variants"

SCAFFOLD_INDEX = """\
# Memory index (compact — detail files loaded on demand)

_(empty — generated by the agentqa-write-test skill's scripts/memory-index.py as notes are added)_
"""

# ---------------------------------------------------------------------------
# identifiers, as they look once step 4 has been done and the human has built
# ---------------------------------------------------------------------------

IDS_INTRO = """\
        btnLogin.accessibilityIdentifier = "login_intro_login_button"
        btnFree.accessibilityIdentifier = "login_intro_free_button"
"""

IDS_LOGINVIEW = """\
        usernameTextField.accessibilityIdentifier = "login_username_field"
        passwordTextField.accessibilityIdentifier = "login_password_field"
        checkBoxTermImgView.accessibilityIdentifier = "login_terms_checkbox"
        termsLink.accessibilityIdentifier = "login_terms_link"
        btnLogin.accessibilityIdentifier = "login_submit_button"
        errorLabel.accessibilityIdentifier = "login_error_label"
"""

IDS_TABBAR = """\
        homeTab.accessibilityIdentifier = "home_home_tab"
        liveTab.accessibilityIdentifier = "home_live_tab"
        profileTab.accessibilityIdentifier = "home_profile_tab"
"""


def with_identifiers():
    """Return {relpath: content} for the Swift files, identifiers added."""
    base = ROOT / "app-repo" / "mytvb2c" / "Sources"
    out = {}

    p = "mytvb2c/Sources/Login/IntroductionContentViewController.swift"
    t = (base / "Login" / "IntroductionContentViewController.swift").read_text(encoding="utf-8")
    t = t.replace('        NotificationPermission.requestIfNeeded()\n',
                  IDS_INTRO + '        NotificationPermission.requestIfNeeded()\n')
    out[p] = t

    p = "mytvb2c/Sources/Login/LoginView.swift"
    t = (base / "Login" / "LoginView.swift").read_text(encoding="utf-8")
    t = t.replace('        errorLabel.isHidden = true\n',
                  '        errorLabel.isHidden = true\n\n' + IDS_LOGINVIEW)
    out[p] = t

    p = "mytvb2c/Sources/Home/MainTabBarController.swift"
    t = (base / "Home" / "MainTabBarController.swift").read_text(encoding="utf-8")
    t = t.replace('        let home = HomeViewController()',
                  IDS_TABBAR + '\n        let home = HomeViewController()')
    out[p] = t
    return out


# ---------------------------------------------------------------------------
# memory notes shared by variants b and c
# ---------------------------------------------------------------------------

FLOW_LOGIN = """\
---
title: login
type: flow
tags: [login, authentication]
summary: Intro → login form → home tab bar, gated on a terms checkbox
last_verified: 2026-07-23
---

# login

## Observations
- [flow-step] launch → notifications permission alert (SpringBoard) → dismissed with "Don't Allow" per reviewer #login
- [flow-step] IntroductionContentViewController → press "Đăng nhập ngay" → LoginViewController #login
- [flow-step] fill username + password, tick "Tôi đồng ý với điều khoản sử dụng", press "Đăng nhập" #login
- [flow-step] success → MainTabBarController with tab bar Trang chủ / Truyền hình / Cá nhân #login
- [assertion] valid credentials + terms ticked lands on the home tab bar #login
- [edge-case] wrong credentials → inline "Sai tên đăng nhập hoặc mật khẩu" under the password field, stays on login #login
- [edge-case] terms unticked → "Vui lòng đồng ý với điều khoản sử dụng", submit is disabled #login
- [native] intro, login and home are native UIKit #login
- [web] the terms sheet is a WKWebView with no native nodes — screenshot only #login
- [quirk] the permission alert is owned by SpringBoard and appears on every wiped launch #login

## Relations
- covers [[intro]]
- covers [[login_form]]
- covers [[home]]
"""

SCREEN_INTRO = """\
---
title: intro
type: screen
tags: [login]
summary: IntroductionContentViewController — login / guest entry point
last_verified: 2026-07-23
---

# intro

## Observations
- [native] IntroductionContentViewController, UIKit xib #login
- [identifier] login_intro_login_button → IntroductionContentViewController.btnLogin; added-unverified 2026-07-23 #login
- [identifier] login_intro_free_button → IntroductionContentViewController.btnFree; added-unverified 2026-07-23 #login
- [quirk] requests notification permission in viewDidLoad, so the alert covers this screen on a wiped launch #login

## Relations
- used-by [[login]]
"""

SCREEN_LOGIN = """\
---
title: login_form
type: screen
tags: [login]
summary: LoginView — username, password, terms checkbox, submit
last_verified: 2026-07-23
---

# login_form

## Observations
- [native] LoginView loaded from a nib by LoginViewController #login
- [identifier] login_username_field → LoginView.usernameTextField; added-unverified 2026-07-23 #login
- [identifier] login_password_field → LoginView.passwordTextField; added-unverified 2026-07-23 #login
- [identifier] login_terms_checkbox → LoginView.checkBoxTermImgView; added-unverified 2026-07-23 #login
- [identifier] login_terms_link → LoginView.termsLink; added-unverified 2026-07-23 #login
- [identifier] login_submit_button → LoginView.btnLogin; added-unverified 2026-07-23 #login
- [identifier] login_error_label → LoginView.errorLabel; added-unverified 2026-07-23 #login
- [quirk] btnLogin.isEnabled is driven by termsAccepted — the checkbox must be tapped before submit #login
- [quirk] errorLabel is hidden until showError(_:) runs #login

## Relations
- used-by [[login]]
"""

SCREEN_HOME = """\
---
title: home
type: screen
tags: [home]
summary: MainTabBarController — the post-login landing surface
last_verified: 2026-07-23
---

# home

## Observations
- [native] MainTabBarController with three tabs #login
- [identifier] home_home_tab → MainTabBarController.homeTab; added-unverified 2026-07-23 #login
- [identifier] home_live_tab → MainTabBarController.liveTab; added-unverified 2026-07-23 #login
- [identifier] home_profile_tab → MainTabBarController.profileTab; added-unverified 2026-07-23 #login

## Relations
- used-by [[login]]
"""

FAILURE_WDA = """\
---
title: wda-timeout-under-load
type: failure
tags: [phantom, infra]
summary: WebDriverAgent session timeout when the host is CPU-saturated
last_verified: 2026-07-20
---

# wda-timeout-under-load

## Observations
- [symptom] `WebDriverAgent process failed to start` or a session that hangs for 60s then dies, with no app-side error #infra
- [cause] a CPU-heavy job (usually `codegraph init`) running while the simulator drives the suite #infra
- [remedy] stop the indexing job, wait for load to drop, re-run the suite once #infra
"""

INDEX_SEEDED = """\
# Memory index (compact — detail files loaded on demand)

## Flows
- **login** — Intro → login form → home tab bar, gated on a terms checkbox
  - covers: intro, login_form, home

## Screens
- **intro** — IntroductionContentViewController — login / guest entry point
- **login_form** — LoginView — username, password, terms checkbox, submit
- **home** — MainTabBarController — the post-login landing surface

## Failures
- **wda-timeout-under-load** — WebDriverAgent session timeout when the host is CPU-saturated

## Env
- env.md — build policy, credential env-var names, simulator gotchas
"""

SESSION_REQUIREMENT = """\
---
title: Session requirement — login
type: session-requirement
updated: 2026-07-23
---
## Request
Write a UI test for the login flow — the user logs in and reaches the home screen.

## Success
The user enters a valid username and password, ticks the terms checkbox, taps
Đăng nhập, and lands on the home screen with the bottom tab bar visible.

## Failure
The app stays on the login screen and shows the inline red text "Sai tên đăng
nhập hoặc mật khẩu" under the password field. It must not bounce back to intro
and must not show a modal.

## Blockers
- Notifications permission alert on first launch after a wipe → reviewer said tap "Don't Allow"
- Đăng nhập stays disabled until the terms checkbox is ticked → tick it before submitting
- No OTP/2FA on the QA account

## Environment / preconditions
staging backend; start logged out; credentials from APP_TEST_USERNAME / APP_TEST_PASSWORD.
"""

RUN_CHECKPOINT = """\
---
run_id: login-2026-07-23-01
current_step: 5
feature: login
updated: 2026-07-23
---

## Added identifiers (awaiting build+verify)
- login_intro_login_button → IntroductionContentViewController.btnLogin
- login_intro_free_button → IntroductionContentViewController.btnFree
- login_username_field → LoginView.usernameTextField
- login_password_field → LoginView.passwordTextField
- login_terms_checkbox → LoginView.checkBoxTermImgView
- login_terms_link → LoginView.termsLink
- login_submit_button → LoginView.btnLogin
- login_error_label → LoginView.errorLabel
- home_home_tab → MainTabBarController.homeTab
- home_live_tab → MainTabBarController.liveTab
- home_profile_tab → MainTabBarController.profileTab

## Hypothesis under test
Valid credentials + ticked terms checkbox lands the user on the home tab bar.

## Blocker
WAITING_FOR_HUMAN_BUILD
"""

# ---------------------------------------------------------------------------
# variant c: an existing test and its failure artifacts
# ---------------------------------------------------------------------------

PAGE_OBJECT = '''\
"""Page objects for the login flow."""
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


class IntroPage:
    LOGIN_BUTTON = (AppiumBy.ACCESSIBILITY_ID, "login_intro_login_button")
    # SpringBoard's, not the app's: it sits outside the app element tree and no
    # accessibilityIdentifier can reach it, so match the visible label.
    PERMISSION_DENY = (AppiumBy.IOS_PREDICATE, 'label == "Don\'t Allow"')

    def __init__(self, driver):
        self.driver = driver

    def dismiss_permission_alert(self):
        """reset_app_data: always restores the permission state, so this prompt
        fires on every launch. Harmless when it is not there."""
        try:
            self.driver.find_element(*self.PERMISSION_DENY).click()
        except NoSuchElementException:
            pass

    def tap_login(self):
        self.driver.find_element(*self.LOGIN_BUTTON).click()


class LoginPage:
    USERNAME = (AppiumBy.ACCESSIBILITY_ID, "login_username_field")
    PASSWORD = (AppiumBy.ACCESSIBILITY_ID, "login_password_field")
    TERMS = (AppiumBy.ACCESSIBILITY_ID, "login_terms_checkbox")
    SUBMIT = (AppiumBy.ACCESSIBILITY_ID, "login_submit_button")
    ERROR = (AppiumBy.ACCESSIBILITY_ID, "login_error_label")

    def __init__(self, driver):
        self.driver = driver

    def login(self, username, password):
        self.driver.find_element(*self.USERNAME).send_keys(username)
        self.driver.find_element(*self.PASSWORD).send_keys(password)
        self.driver.find_element(*self.TERMS).click()
        self.driver.find_element(*self.SUBMIT).click()

    def error_text(self):
        return self.driver.find_element(*self.ERROR).text


class HomePage:
    HOME_TAB = (AppiumBy.ACCESSIBILITY_ID, "home_home_tab")

    def __init__(self, driver):
        self.driver = driver

    def is_loaded(self):
        return self.driver.find_element(*self.HOME_TAB).is_displayed()
'''

TEST_FILE = '''\
"""Login flow UI tests."""
import os

import pytest

from pages.login_page import HomePage, IntroPage, LoginPage


@pytest.fixture
def credentials():
    user = os.environ.get("APP_TEST_USERNAME")
    pwd = os.environ.get("APP_TEST_PASSWORD")
    if not user or not pwd:
        pytest.skip("APP_TEST_USERNAME / APP_TEST_PASSWORD not set")
    return user, pwd


def test_login_happy_path(driver, credentials):
    """Valid credentials + accepted terms land the user on the home tab bar."""
    username, password = credentials
    intro = IntroPage(driver)
    intro.dismiss_permission_alert()
    intro.tap_login()
    LoginPage(driver).login(username, password)
    assert HomePage(driver).is_loaded(), "expected the home tab bar after login"


def test_login_rejects_wrong_password(driver, credentials):
    """A wrong password keeps the user on the login screen with an inline error."""
    username, _ = credentials
    intro = IntroPage(driver)
    intro.dismiss_permission_alert()
    intro.tap_login()
    page = LoginPage(driver)
    page.login(username, "definitely-not-the-password")
    assert page.error_text() == "Sai tên đăng nhập hoặc mật khẩu"
'''

FAILED_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
  <XCUIElementTypeApplication type="XCUIElementTypeApplication" name="MyTV" label="MyTV" enabled="true" x="0" y="0" width="393" height="852">
    <XCUIElementTypeAlert type="XCUIElementTypeAlert" name="THÔNG BÁO" label="THÔNG BÁO" enabled="true" visible="true" x="43" y="330" width="307" height="192">
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" name="THÔNG BÁO" label="THÔNG BÁO" value="" enabled="true" visible="true"/>
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" name="Đã có lỗi xảy ra, Quý khách vui lòng thử lại sau! (58)" label="Đã có lỗi xảy ra, Quý khách vui lòng thử lại sau! (58)" value="" enabled="true" visible="true"/>
      <XCUIElementTypeButton type="XCUIElementTypeButton" name="Đóng" label="Đóng" enabled="true" visible="true"/>
    </XCUIElementTypeAlert>
    <XCUIElementTypeButton type="XCUIElementTypeButton" name="login_intro_login_button" label="Đăng nhập ngay" enabled="true" visible="false" x="24" y="640" width="345" height="48"/>
    <XCUIElementTypeButton type="XCUIElementTypeButton" name="login_intro_free_button" label="Xem miễn phí" enabled="true" visible="false" x="24" y="700" width="345" height="48"/>
  </XCUIElementTypeApplication>
</AppiumAUT>
"""

VARIANTS = {}

VARIANTS["a"] = {
    ".agentqa/memory/index.md": SCAFFOLD_INDEX,
}

VARIANTS["b"] = {
    **with_identifiers(),
    ".agentqa/memory/index.md": INDEX_SEEDED,
    ".agentqa/memory/flows/login.md": FLOW_LOGIN,
    ".agentqa/memory/screens/intro.md": SCREEN_INTRO,
    ".agentqa/memory/screens/login_form.md": SCREEN_LOGIN,
    ".agentqa/memory/screens/home.md": SCREEN_HOME,
    ".agentqa/memory/failures/wda-timeout-under-load.md": FAILURE_WDA,
    ".agentqa/memory/.session-requirement.md": SESSION_REQUIREMENT,
    ".agentqa/memory/.run-checkpoint.md": RUN_CHECKPOINT,
}


def _verified(text):
    return text.replace("added-unverified 2026-07-23", "verified-in-hierarchy 2026-07-23")


VARIANTS["c"] = {
    **with_identifiers(),
    ".agentqa/memory/index.md": INDEX_SEEDED,
    ".agentqa/memory/flows/login.md": FLOW_LOGIN,
    ".agentqa/memory/screens/intro.md": _verified(SCREEN_INTRO),
    ".agentqa/memory/screens/login_form.md": _verified(SCREEN_LOGIN),
    ".agentqa/memory/screens/home.md": _verified(SCREEN_HOME),
    ".agentqa/memory/failures/wda-timeout-under-load.md": FAILURE_WDA,
    "AutomationTests/pages/login_page.py": PAGE_OBJECT,
    "AutomationTests/tests/test_login.py": TEST_FILE,
    "AutomationTests/artifacts/failed_test_login_happy_path.xml": FAILED_XML,
    ".agentqa/.eval-backend": "error_404\n",
}


# ---------------------------------------------------------------------------
# intent layer: product artifacts (the `docs:` block)
#
# a-docs           an SRD that matches the build -> should pre-fill clarify
# a-docs-conflict  an SRD that has drifted from the build -> live must win
# ---------------------------------------------------------------------------

CONFIG_WITH_DOCS = """\
# Project configuration for the agentqa skill (.agentqa/config.yml)
# Facts about THIS project that the generic skill must not hardcode.

platform: ios
bundle_id: com.vnpt.media.mobileb2c
test_dir: AutomationTests

build:
  policy: human
  note: "Manual builds required — signing and package configuration"

reset_app_data: always   # always (DEFAULT) = wipe the app's local data before launch

credentials:
  username_env: APP_TEST_USERNAME   # env var NAMES only — never values
  password_env: APP_TEST_PASSWORD

# Product artifacts — intent, not truth. Read-only.
docs:
  - docs/product/*.md

identifier_convention: screen_element_type   # e.g. login_username_field, home_profile_button

appium:
  port: 4723
"""

# Matches the shipped build. Every claim here is confirmable live.
SPEC_ACCURATE = """\
# SRD-014 — Đăng nhập (Login)

| | |
|---|---|
| Owner | Trang N. (PM) |
| Status | Approved — released in 4.8.0 |
| Last reviewed | 2026-05-12 |

## 1. Scope

Cho phép người dùng đã có tài khoản MyTV đăng nhập trên iOS để truy cập nội dung
thuê bao. Guest (chưa đăng nhập) vẫn xem được nội dung miễn phí.

## 2. Entry points

Người dùng có thể vào màn hình đăng nhập từ hai nơi:

1. **Màn hình giới thiệu (Introduction)** — nút "Đăng nhập ngay".
2. **Tab Cá nhân khi đang ở chế độ guest** — nút "Đăng nhập để tiếp tục".

Cả hai đều mở cùng một `LoginViewController`.

## 3. Preconditions

- Thiết bị đã cài app, người dùng đang ở trạng thái **chưa đăng nhập**.
- Backend staging hoạt động bình thường.
- Tài khoản QA không bật OTP/2FA.

## 4. Main flow (happy path)

1. Mở app. Ở lần mở đầu tiên sau khi cài/xoá dữ liệu, hệ thống hiển thị
   **hộp thoại xin quyền thông báo** của iOS. Người dùng chọn một trong hai.
2. Nhấn "Đăng nhập ngay" → màn hình đăng nhập.
3. Nhập **Tên đăng nhập** và **Mật khẩu**.
4. **Tích vào ô "Tôi đồng ý với điều khoản sử dụng"** — nút "Đăng nhập" bị
   **disabled** cho tới khi ô này được tích. Đây là yêu cầu pháp lý, bắt buộc.
5. Nhấn "Đăng nhập".
6. Thành công → chuyển sang **màn hình chính có thanh tab dưới cùng**
   (Trang chủ / Truyền hình / Cá nhân).

## 5. Alternate & error flows

| # | Điều kiện | Kết quả mong đợi |
|---|---|---|
| 5.1 | Sai tên đăng nhập hoặc mật khẩu | **Ở lại màn hình đăng nhập**, hiển thị dòng chữ đỏ **"Sai tên đăng nhập hoặc mật khẩu"** ngay dưới ô mật khẩu. Không có popup, không quay về màn hình giới thiệu. |
| 5.2 | Chưa tích ô điều khoản | Nút "Đăng nhập" disabled; nếu submit vẫn hiện "Vui lòng đồng ý với điều khoản sử dụng". |
| 5.3 | Nhấn "Điều khoản sử dụng" | Mở sheet điều khoản (trang web nhúng), có nút "Xong" để đóng. |

## 6. Acceptance criteria

- [x] AC-1: Đăng nhập đúng thông tin + đã tích điều khoản → vào được màn hình
      chính và nhìn thấy thanh tab.
- [x] AC-2: Sai mật khẩu → ở lại màn hình đăng nhập kèm thông báo lỗi inline.
- [x] AC-3: Nút đăng nhập disabled khi chưa tích điều khoản.
- [x] AC-4: Không lưu mật khẩu vào log hay file trong repo.
"""

# Drifted from the build on purpose. Three concrete divergences:
#   - claims NO terms checkbox (live: mandatory, gates the submit button)
#   - claims a MODAL + bounce to intro on bad credentials
#     (live: inline error, stays on the login screen)
#   - claims a "Ghi nhớ đăng nhập" toggle that does not exist live
SPEC_CONFLICT = """\
# SRD-014 — Đăng nhập (Login)

| | |
|---|---|
| Owner | Trang N. (PM) |
| Status | Draft — viết trước khi bàn giao cho team iOS |
| Last reviewed | 2025-11-03 |

## 1. Scope

Cho phép người dùng đã có tài khoản MyTV đăng nhập trên iOS để truy cập nội dung
thuê bao.

## 2. Entry point

Từ **màn hình giới thiệu (Introduction)** — nút "Đăng nhập ngay".

## 3. Preconditions

- Người dùng đang ở trạng thái chưa đăng nhập.
- Backend staging hoạt động bình thường.

## 4. Main flow (happy path)

1. Mở app → màn hình giới thiệu.
2. Nhấn "Đăng nhập ngay" → màn hình đăng nhập.
3. Nhập **Tên đăng nhập** và **Mật khẩu**.
4. Bật tuỳ chọn **"Ghi nhớ đăng nhập"** nếu muốn giữ phiên đăng nhập cho lần sau.
5. Nhấn "Đăng nhập".
6. Thành công → chuyển sang **Dashboard**, hiển thị popup chào mừng
   "Chào mừng quý khách trở lại".

## 5. Alternate & error flows

| # | Điều kiện | Kết quả mong đợi |
|---|---|---|
| 5.1 | Sai tên đăng nhập hoặc mật khẩu | Hiển thị **hộp thoại (modal)** với tiêu đề "Tài khoản không hợp lệ" và nút "Đóng". Sau khi đóng, **quay về màn hình giới thiệu**. |
| 5.2 | Mất kết nối mạng | Toast "Không có kết nối mạng". |

## 6. Acceptance criteria

- [ ] AC-1: Đăng nhập đúng thông tin → vào Dashboard và thấy popup chào mừng.
- [ ] AC-2: Sai mật khẩu → hiện modal "Tài khoản không hợp lệ", quay về màn
      hình giới thiệu.
- [ ] AC-3: Tuỳ chọn "Ghi nhớ đăng nhập" giữ được phiên sau khi tắt app.
"""

VARIANTS["a-docs"] = {
    ".agentqa/memory/index.md": SCAFFOLD_INDEX,
    ".agentqa/config.yml": CONFIG_WITH_DOCS,
    "docs/product/login-flow.md": SPEC_ACCURATE,
}

VARIANTS["a-docs-conflict"] = {
    ".agentqa/memory/index.md": SCAFFOLD_INDEX,
    ".agentqa/config.yml": CONFIG_WITH_DOCS,
    "docs/product/login-flow.md": SPEC_CONFLICT,
}


def main():
    for name, files in VARIANTS.items():
        for rel, content in files.items():
            p = VAR / name / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
        # binary artifact
        if name == "c":
            png = VAR / name / "AutomationTests/artifacts/failed_test_login_happy_path.png"
            png.write_bytes(b"\x89PNG\r\n\x1a\n<mock failure screenshot: THONG BAO alert>")
        print(f"variant {name}: {len(files)} files")


if __name__ == "__main__":
    sys.exit(main())
