"""Shared schema for the .agentqa/memory/ scripts. Stdlib only.

One definition of what a note may contain, imported by memory-write.py,
memory-index.py and memory-lint.py, so the writer can never accept something the
linter rejects (or vice versa). The schema itself is documented in
references/memory-model.md — this module is its executable half.
"""
import re
from datetime import date
from pathlib import Path

# --- Layout -----------------------------------------------------------------
# The persistent store: the only places a Capture may land. `index.md` is
# regenerated from these, and the two dotfiles are one session's scratch state,
# so a write reaching either would be erased or would leak session-scoped claims
# into the store that later runs trust as a map.
PERSISTENT_DIRS = ("flows", "screens", "failures")
PERSISTENT_FILES = ("env.md",)
GENERATED_FILES = ("index.md",)
EPHEMERAL_FILES = (".session-requirement.md", ".run-checkpoint.md")

NOTE_TYPES = frozenset({"flow", "screen", "failure", "env"})

CATEGORIES = frozenset({
    "flow-step", "assertion", "native", "web", "identifier", "quirk",
    "edge-case", "symptom", "cause", "remedy", "gotcha", "credential-env",
})

ID_STATUSES = frozenset({"added-unverified", "verified-in-hierarchy"})
STALE_DAYS = 30

OBS_HEADER = "## Observations"
OBS_RE = re.compile(r"^- \[([^\]\s]+)\]\s*(.*)$")
TAG_RE = re.compile(r"#([A-Za-z0-9][\w-]*)")

# <name> → <file/symbol>; <status> <YYYY-MM-DD> [#tags]
IDENTIFIER_RE = re.compile(
    r"^(?P<name>\S+)\s*→\s*(?P<placement>[^;]+?)\s*;\s*"
    r"(?P<status>[a-z-]+)\s+(?P<date>\d{4}-\d{2}-\d{2})\s*(?P<tags>.*)$"
)


class MemoryPathError(ValueError):
    """A path that is not part of the persistent store."""


def resolve_persistent(memory_dir, note):
    """Resolve `note` to a path inside the persistent store, or raise.

    Everything a Capture writes belongs in flows/, screens/, failures/ or
    env.md. Refusing anything else here is what stops an UPDATE from silently
    rewriting the generated index, or from editing a session requirement note
    whose whole purpose is to be thrown away unverified.
    """
    memory_dir = Path(memory_dir).resolve()
    name = note if str(note).endswith(".md") else f"{note}.md"
    p = Path(name)
    target = (p if p.is_absolute() else memory_dir / p).resolve()

    try:
        rel = target.relative_to(memory_dir)
    except ValueError:
        raise MemoryPathError(
            f"{target} is outside the memory store ({memory_dir})"
        ) from None

    parts = rel.parts
    if len(parts) == 1:
        if parts[0] in PERSISTENT_FILES:
            return target
        if parts[0] in GENERATED_FILES:
            raise MemoryPathError(
                f"{rel} is generated by memory-index.py — edits are erased on the "
                f"next rebuild. Write to the note it is built from instead."
            )
        if parts[0] in EPHEMERAL_FILES:
            raise MemoryPathError(
                f"{rel} is session state, deleted when the session ends, and it "
                f"holds claims that have not been observed live. Capture what you "
                f"verified into flows/, screens/ or failures/ instead."
            )
        raise MemoryPathError(
            f"{rel} is not part of the persistent store — expected "
            f"{'/, '.join(PERSISTENT_DIRS)}/ or {', '.join(PERSISTENT_FILES)}"
        )
    if parts[0] not in PERSISTENT_DIRS:
        raise MemoryPathError(
            f"{rel} is not part of the persistent store — expected "
            f"{'/, '.join(PERSISTENT_DIRS)}/ or {', '.join(PERSISTENT_FILES)}"
        )
    return target


def iter_persistent_notes(memory_dir):
    """Every note a Capture may read or write, in a stable order."""
    memory_dir = Path(memory_dir)
    for d in PERSISTENT_DIRS:
        sub = memory_dir / d
        if sub.is_dir():
            for p in sorted(sub.glob("*.md")):
                yield p
    for f in PERSISTENT_FILES:
        p = memory_dir / f
        if p.is_file():
            yield p


def parse_obs(line):
    """('category', 'text') for an observation line, else None."""
    m = OBS_RE.match(line.rstrip("\n"))
    if not m:
        return None
    category = m.group(1)
    # `- [label](url)` is a markdown link, not an observation. Restricting to
    # known categories tells the two apart without guessing.
    if category not in CATEGORIES:
        return None
    return category, m.group(2)


def iter_observations(memory_dir):
    """(path, lineno, category, text) over the persistent store only."""
    for p in iter_persistent_notes(memory_dir):
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            parsed = parse_obs(line)
            if parsed:
                yield p, i, parsed[0], parsed[1]


def parse_front(text):
    front = {}
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            for line in text[3:end].splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    front[k.strip()] = v.strip().strip('"')
    return front


def tags_of(text):
    return set(TAG_RE.findall(text))


def age_days(datestr, today=None):
    try:
        return ((today or date.today()) - date.fromisoformat(datestr)).days
    except (ValueError, TypeError):
        return None


# --- Secret detection -------------------------------------------------------
# The store is committed and team-shared, so a value that lands here is a value
# in git history. These patterns aim at the shapes a real leak takes; they are a
# safety net under the "env-var names only" rule, not a replacement for it.
_SECRET_KEYWORDS = (
    r"password|passwd|pwd|secret|token|api[-_ ]?key|apikey|access[-_ ]?key"
    r"|private[-_ ]?key|client[-_ ]?secret|credential"
)
_KEYVALUE_RE = re.compile(rf"(?i)\b({_SECRET_KEYWORDS})s?\b\s*[:=]\s*(\S+)")
_PLACEHOLDER_RE = re.compile(
    r"^(?:[<{$(\[]|\*{2,}|x{3,}$|\.{3}|…|env|redacted|n/?a$|none$|tbd$)", re.I)
_ENVVAR_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")

_TOKEN_PATTERNS = (
    ("OpenAI-style key", re.compile(r"\bsk-[A-Za-z0-9]{16,}")),
    ("GitHub token", re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}")),
    ("GitHub PAT", re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}")),
    ("Slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("AWS access key id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{20,}")),
    ("JWT", re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.")),
    ("private key block", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
)

_EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w-]+\.[A-Za-z]{2,}\b")


def _is_placeholder(value):
    v = value.strip().strip("`'\"").rstrip(".,;")
    if not v:
        return True
    return bool(_PLACEHOLDER_RE.match(v) or _ENVVAR_RE.match(v))


def secret_findings(text):
    """[(severity, message)] for credential-shaped content. severity: error|warn.

    Env-var *names* (`APP_TEST_PASSWORD`) and placeholders (`<fill me>`) are the
    documented way to reference a credential, so they pass; a literal value does
    not.
    """
    out = []
    for label, pattern in _TOKEN_PATTERNS:
        if pattern.search(text):
            out.append(("error", f"looks like a committed secret ({label})"))
    for m in _KEYVALUE_RE.finditer(text):
        if not _is_placeholder(m.group(2)):
            out.append((
                "error",
                f"'{m.group(1)}' is given a literal value ({m.group(2)!r}) — record "
                f"the env-var NAME instead",
            ))
    for m in _EMAIL_RE.finditer(text):
        out.append((
            "warn",
            f"contains an email address ({m.group(0)}) — if that's a test account, "
            f"record its env-var name instead",
        ))
    return out
